{"timestamp":"2025-06-05T16:21:02.057981","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-06-05T16:21:02.064188","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/extract_data_from_gcp_rev1.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-06-05T16:21:35.090513","level":"error","event":"Process timed out, PID: 155","logger":"airflow.utils.timeout.TimeoutPosix"}
{"timestamp":"2025-06-05T16:21:35.120087Z","level":"error","event":"Exception ignored in: <function _collection_gced at 0x7272c0fceca0>","chan":"stderr","logger":"task"}
{"timestamp":"2025-06-05T16:21:35.121281Z","level":"error","event":"Traceback (most recent call last):","chan":"stderr","logger":"task"}
{"timestamp":"2025-06-05T16:21:35.123519Z","level":"error","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/event/registry.py\", line 53, in _collection_gced","chan":"stderr","logger":"task"}
{"timestamp":"2025-06-05T16:21:35.124381Z","level":"error","event":"    def _collection_gced(ref):","chan":"stderr","logger":"task"}
{"timestamp":"2025-06-05T16:21:35.124987Z","level":"error","event":"","chan":"stderr","logger":"task"}
{"timestamp":"2025-06-05T16:21:35.125463Z","level":"error","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py\", line 69, in handle_timeout","chan":"stderr","logger":"task"}
{"timestamp":"2025-06-05T16:21:35.153398Z","level":"error","event":"    raise AirflowTaskTimeout(self.error_message)","chan":"stderr","logger":"task"}
{"timestamp":"2025-06-05T16:21:35.154878Z","level":"error","event":"airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/extract_data_from_gcp_rev1.py after 30.0s.","chan":"stderr","logger":"task"}
{"timestamp":"2025-06-05T16:21:35.156013Z","level":"error","event":"Please take a look at these docs to improve your DAG import time:","chan":"stderr","logger":"task"}
{"timestamp":"2025-06-05T16:21:35.156623Z","level":"error","event":"* https://airflow.apache.org/docs/apache-airflow/3.0.0/best-practices.html#top-level-python-code","chan":"stderr","logger":"task"}
{"timestamp":"2025-06-05T16:21:35.157343Z","level":"error","event":"* https://airflow.apache.org/docs/apache-airflow/3.0.0/best-practices.html#reducing-dag-complexity, PID: 155","chan":"stderr","logger":"task"}
{"timestamp":"2025-06-05T16:21:53.432380","level":"info","event":"Secrets backends loaded for worker","count":1,"backend_classes":["EnvironmentVariablesBackend"],"logger":"supervisor"}
{"timestamp":"2025-06-05T16:22:16.371203","level":"error","event":"Error response from the API Server","logger":"task"}
{"timestamp":"2025-06-05T16:22:16.372972","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"AirflowRuntimeError","exc_value":"API_SERVER_ERROR: {'status_code': 409, 'message': 'Server returned error', 'detail': {'detail': {'reason': 'Unique constraint violation', 'statement': 'INSERT INTO rendered_task_instance_fields (dag_id, task_id, run_id, map_index, rendered_fields, k8s_pod_yaml) VALUES (%(dag_id)s, %(task_id)s, %(run_id)s, %(map_index)s, %(rendered_fields)s, %(k8s_pod_yaml)s)', 'orig_error': 'duplicate key value violates unique constraint \"rendered_task_instance_fields_pkey\"\\nDETAIL:  Key (dag_id, task_id, run_id, map_index)=(extract_customers_data, list_files, scheduled__2025-06-05T16:20:54.048338+00:00, -1) already exists.\\n'}}}","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":825,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1088,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":408,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/gcs.py","lineno":240,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py","lineno":280,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py","lineno":64,"name":"get_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py","lineno":472,"name":"get_connection_from_secrets"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/definitions/connection.py","lineno":142,"name":"get"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/context.py","lineno":158,"name":"_get_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":643,"name":"get_message"}]}]}
{"timestamp":"2025-06-05T16:22:16.556164","level":"error","event":"Top level error","logger":"task","error_detail":[{"exc_type":"TypeError","exc_value":"Expected XComResult, received: <class 'airflow.sdk.execution_time.comms.ErrorResponse'> error=<ErrorType.CONNECTION_NOT_FOUND: 'CONNECTION_NOT_FOUND'> detail={'conn_id': 'google_cloud_default'} type='ErrorResponse'","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1216,"name":"main"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1154,"name":"finalize"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/links/base.py","lineno":55,"name":"get_link"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/xcom.py","lineno":142,"name":"get_value"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/xcom.py","lineno":263,"name":"get_one"}]}]}
{"timestamp":"2025-06-05T16:22:16.702056Z","level":"warning","event":"Process exited abnormally","exit_code":1,"logger":"task"}
